---
title: "NetCDF"
author: "Shayne O'Brien"
date: "January 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("ncdf4")
library(ncdf4)
library(dplyr)
library(tidyr)
library(ggplot2)
```
# Read in the file
```{r}
nc <- nc_open("WG2013CTD.nc")

```
```{r}
vars <- attributes(nc$var)$names
vars
```

```{r}
dims <- attributes(nc$dim)$names
dims
```

```{r}
salinity <- ncvar_get(nc, "sal")
time <- ncvar_get(nc, "time")
depth <- ncvar_get(nc, "z")
```
# Reformat the output
```{r}
time <- as.POSIXct((time + 719529)*86400, origin = "1970-01-01", tz = "UTC")
```

## Coerce matrix to data frame

```{r}
# coerce matrix to data frame
salinity_data <- as.data.frame(salinity) 
```
## Assign column names to depth values

```{r}
names(salinity_data) <- as.character(depth)
```
## Reshape data and add time

```{r}
salinity_data_long <- salinity_data %>% 
  mutate(time=time) %>% 
  gather(key= "depth", value = "salinity", -time) %>% 
  mutate(depth = as.numeric(depth))
  
```


# Plots

```{r}
ggplot(salinity_data_long, mapping = aes(x = salinity, y= depth, color = time))+
  geom_line() +
  scale_y_reverse()
```

